[package]
name = "iana-cbor"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "IANA CBOR registry definitions"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tiagomanczak/iana-rs"
keywords = ["iana", "suit", "cbor", "no-std", "embedded"]
categories = ["no-std", "embedded", "encoding"]


[dependencies]

[dev-dependencies]

[lints]
workspace = true
